
[/Script/CommonUI.CommonUISettings]
CommonButtonAcceptKeyHandling=TriggerClick

[ConsoleVariables]
CommonUI.CheckKeyboardFocusAndParentage=1
CommonUI.DisallowUserFocusedWidgetForPendingFocusRecipient=1
CommonUI.FallbackToDesiredOnAutoRestoreFailure=1

[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=482996DB4194AB11462D189A17A8DFC8

[/Script/Framework.FWMainMenuPlayerController]
GameplayLevel=/Game/Map/DefaultMap.DefaultMap

[/Script/UnrealEd.ProjectPackagingSettings]
+MapsToCook=(FilePath="/Game/Map/MainMenu")
+MapsToCook=(FilePath="/Game/Map/DefaultMap")
; Gameplay input actions are loaded by path in FWPlayerController.
+DirectoriesToAlwaysCook=(Path="/Game/Input")
